runtime: python
env: flex
entrypoint: gunicorn -b :$PORT olivaw.main:app

runtime_config:
  python_version: 3

automatic_scaling:
  max_num_instances: 1
  min_num_instances: 1

health_check:
  enable_health_check: True
  check_interval_sec: 1
  timeout_sec: 1
